version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: